kind: Deployment
apiVersion: apps/v1
metadata:
   name: webapp-deploy
spec:
   replicas: 3
   selector:     
      matchLabels:
         app: webpage
   template:
      metadata:
         labels:
            app: webpage
      spec:
         containers:
            - name: webapp-deployment
              image: vikashashoke/mydemoapplication
              imagePullPolicy: Always
              ports:
               - containerPort: 80
